#pragma once
#include <array>

namespace consts {

	// Fields array corresponds to the chcks and txts.
	constexpr auto FIELDS_NAME4 = std::array{
		L"TPE1",
		L"TIT2",
		L"TIT3",
		L"TALB",
		L"TRCK",
		L"TYER",
		L"TCON",
		L"TPE3",
		L"TPUB",
		L"TOPE",
		L"TOAL",
		L"TORY",
		L"TCOM",
		L"TEXT",
		L"COMM",
	};

	constexpr auto GENRES = std::array{
		L"Alternative rock",
		L"Axé", // note: the file must be saved as Windows-1252, otherwise we'll get garbled chars
		L"Black metal",
		L"Bluegrass",
		L"Blues",
		L"Blues rock",
		L"Brega",
		L"Britpop",
		L"Country",
		L"Dance",
		L"Death metal",
		L"Disco",
		L"Doom metal",
		L"Folk metal",
		L"Forró",
		L"Glam metal",
		L"Gothic metal",
		L"Grindcore",
		L"Groove metal",
		L"Grunge",
		L"Guitar rock",
		L"Hard rock",
		L"Hardcore",
		L"Heavy metal",
		L"Hip hop",
		L"Indie rock",
		L"Jazz",
		L"Manguebeat",
		L"Nu metal",
		L"Pop",
		L"Pop rock",
		L"Post-punk",
		L"Power ballad",
		L"Power metal",
		L"Progressive metal",
		L"Progressive rock",
		L"Psychedelic rock",
		L"Punk rock",
		L"R&B",
		L"Rap metal",
		L"Reggae",
		L"Rock",
		L"Samba",
		L"Sertanejo",
		L"Smooth jazz",
		L"Soul",
		L"Southern rock",
		L"Symphonic metal",
		L"Synthpop",
		L"Thrash metal",
		L"Viking metal",
	};

}
