#include "DlgEdit.h"
#include "../res/resource.h"

DlgEdit::FieldInfo DlgEdit::_Fields[] = {
	{CHK_ARTIST, L"TPE1"},
	{CHK_TITLE, L"TIT2"},
	{CHK_SUBTITLE, L"TIT3"},
	{CHK_ALBUM, L"TALB"},
	{CHK_TRACK, L"TRCK"},
	{CHK_YEAR, L"TYER"},
	{CHK_GENRE, L"TCON"},
	{CHK_PERFORMER, L"TPE3"},
	{CHK_PUBLISHER, L"TPUB"},
	{CHK_OARTIST, L"TOPE"},
	{CHK_OALBUM, L"TOAL"},
	{CHK_OYEAR, L"TORY"},
	{CHK_COMPOSER, L"TCOM"},
	{CHK_LYRICIST, L"TEXT"},
	{CHK_COMMENT, L"COMM"},
};

LPCWSTR DlgEdit::_Genres[] = {
	L"Alternative rock",
	L"Axé",
	L"Black metal",
	L"Bluegrass",
	L"Blues",
	L"Blues rock",
	L"Brega",
	L"Britpop",
	L"Country",
	L"Dance",
	L"Death metal",
	L"Disco",
	L"Doom metal",
	L"Folk metal",
	L"Forró",
	L"Glam metal",
	L"Gothic metal",
	L"Grindcore",
	L"Groove metal",
	L"Grunge",
	L"Guitar rock",
	L"Hard rock",
	L"Hardcore",
	L"Heavy metal",
	L"Hip hop",
	L"Indie rock",
	L"Jazz",
	L"Manguebeat",
	L"Nu metal",
	L"Pop",
	L"Pop rock",
	L"Post-punk",
	L"Power ballad",
	L"Power metal",
	L"Progressive metal",
	L"Progressive rock",
	L"Psychedelic rock",
	L"Punk rock",
	L"R&B",
	L"Rap metal",
	L"Reggae",
	L"Rock",
	L"Samba",
	L"Sertanejo",
	L"Smooth jazz",
	L"Soul",
	L"Southern rock",
	L"Symphonic metal",
	L"Synthpop",
	L"Thrash metal",
	L"Viking metal",
};
