//! Declaration of resource IDs used in resources.res file, to be loaded
//! throughout the application.

use winsafe::seq_ids;

seq_ids! {
	ICO_APP = 101;
	ACC_MAIN
}

seq_ids! {
	MNU_FILE = 200;
	MNU_FILE_OPEN // Ctrl+O
	MNU_FILE_EDIT
	MNU_FILE_REMOVE
	MNU_FILE_RESAVE
	MNU_FILE_DELRG
	MNU_FILE_DELRGART
	MNU_FILE_ABOUT // F1
}

seq_ids! {
	MNU_FRAMES = 300;
	MNU_FRAMES_MOVEUP
	MNU_FRAMES_MOVEDOWN
	MNU_FRAMES_DELETE
}

seq_ids! {
	MNU_PIC = 400;
	MNU_PIC_INSERT
	MNU_PIC_EXTRACT
	MNU_PIC_DELETE
}

seq_ids! {
	DLG_MAIN = 1000;
	LST_FILES
}

seq_ids! {
	DLG_EDIT = 2000;
	CHK_ARTIST
	TXT_ARTIST
	CHK_TITLE
	TXT_TITLE
	CHK_SUBTITLE
	TXT_SUBTITLE
	CHK_ALBUM
	TXT_ALBUM
	CHK_TRACK
	TXT_TRACK
	CHK_YEAR
	TXT_YEAR
	CHK_GENRE
	CMB_GENRE
	CHK_PERFORMER
	TXT_PERFORMER
	CHK_PUBLISHER
	TXT_PUBLISHER
	CHK_ORIG_ARTIST
	TXT_ORIG_ARTIST
	CHK_ORIG_ALBUM
	TXT_ORIG_ALBUM
	CHK_ORIG_YEAR
	TXT_ORIG_YEAR
	CHK_COMPOSER
	TXT_COMPOSER
	CHK_LYRICIST
	TXT_LYRICIST
	CHK_COMMENT
	TXT_COMMENT
	CHK_PICTURE
	LBL_PICTURE
	BTN_UNCHECK_ALL
	BTN_CHECK_FILLED
	LST_FRAMES
}
